/* eslint-disable no-unused-vars */
export enum ENUM_APPOINTMENT_STATUSES {
    SCHEDULED = 'SCHEDULED',
    CANCELLED = 'CANCELLED',
    COMPLETED = 'COMPLETED',
    REQUESTED = 'REQUESTED',
    REJECTED = 'REJECTED',
}

export const APPOINTMENT_STATUS_COLORS: Record<ENUM_APPOINTMENT_STATUSES, string> = {
    [ENUM_APPOINTMENT_STATUSES.SCHEDULED]: 'info',
    [ENUM_APPOINTMENT_STATUSES.CANCELLED]: 'error',
    [ENUM_APPOINTMENT_STATUSES.COMPLETED]: 'secondary',
    [ENUM_APPOINTMENT_STATUSES.REQUESTED]: 'warning',
    [ENUM_APPOINTMENT_STATUSES.REJECTED]: 'error',
}

export const APPOINTMENT_STATUS_BGCOLORS: Record<ENUM_APPOINTMENT_STATUSES, string> = {
    [ENUM_APPOINTMENT_STATUSES.SCHEDULED]: '#329DFF',
    [ENUM_APPOINTMENT_STATUSES.CANCELLED]: '#c62828',
    [ENUM_APPOINTMENT_STATUSES.COMPLETED]: '#4CD48B',
    [ENUM_APPOINTMENT_STATUSES.REQUESTED]: '#ffc107',
    [ENUM_APPOINTMENT_STATUSES.REJECTED]: '#c62828',
}
