export enum ENUM_SUBSCRIPTION_STATUSES {
    NOTACTIVE = 'NOTACTIVE',
    ACTIVE = 'ACTIVE',
    PAUSED = 'PAUSED',
}


export const SUBSCRIPTION_STATUS = {
    [ENUM_SUBSCRIPTION_STATUSES.ACTIVE]: '#00e676',  
    [ENUM_SUBSCRIPTION_STATUSES.NOTACTIVE]: '#757575', 
    [ENUM_SUBSCRIPTION_STATUSES.PAUSED]: '#1C2F59', 
    // ... add more if needed
}
